AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cloud Optimizer - One-click deployment using nested stacks (requires S3 bucket for nested templates)'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment Configuration
        Parameters:
          - EnvironmentName
      - Label:
          default: Nested Stack Configuration
        Parameters:
          - TemplateS3Bucket
          - TemplateS3KeyPrefix
      - Label:
          default: Database Configuration
        Parameters:
          - DBInstanceClass
          - DBPassword
          - AllocatedStorage
          - MultiAZ
      - Label:
          default: ECR Configuration
        Parameters:
          - CreateECRRepository
          - ImageTagMutability
      - Label:
          default: ECS Configuration
        Parameters:
          - ContainerImage
          - ContainerCpu
          - ContainerMemory
          - DesiredCount
      - Label:
          default: Security Configuration
        Parameters:
          - JWTSecretKey

Parameters:
  EnvironmentName:
    Description: Environment name to prefix all resources
    Type: String
    Default: cloud-optimizer
    MinLength: 1
    MaxLength: 32
    AllowedPattern: '[a-z][a-z0-9-]*'
    ConstraintDescription: Must start with a letter, contain only lowercase letters, numbers, and hyphens

  TemplateS3Bucket:
    Description: S3 bucket containing nested CloudFormation templates
    Type: String
    MinLength: 1
    ConstraintDescription: Must specify S3 bucket name

  TemplateS3KeyPrefix:
    Description: S3 key prefix for nested templates (e.g., cloudformation/nested/)
    Type: String
    Default: cloudformation/nested/
    ConstraintDescription: Must end with a forward slash

  DBInstanceClass:
    Description: Database instance type
    Type: String
    Default: db.t3.micro
    AllowedValues:
      - db.t3.micro
      - db.t3.small
      - db.t3.medium
      - db.t4g.micro
      - db.t4g.small
      - db.t4g.medium

  DBPassword:
    Description: Database master password (min 8 characters)
    Type: String
    NoEcho: true
    MinLength: 8
    MaxLength: 41
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: Must contain only alphanumeric characters

  AllocatedStorage:
    Description: Database storage size in GB
    Type: Number
    Default: 20
    MinValue: 20
    MaxValue: 100

  MultiAZ:
    Description: Enable Multi-AZ deployment for high availability
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

  CreateECRRepository:
    Description: Create an ECR repository for Cloud Optimizer images
    Type: String
    Default: true
    AllowedValues:
      - true
      - false

  ImageTagMutability:
    Description: ECR image tag mutability (IMMUTABLE recommended for production)
    Type: String
    Default: IMMUTABLE
    AllowedValues:
      - MUTABLE
      - IMMUTABLE

  ContainerImage:
    Description: Docker image to deploy (use your ECR/Docker Hub image)
    Type: String
    Default: public.ecr.aws/docker/library/nginx:latest

  ContainerCpu:
    Description: CPU units for the container (256 = 0.25 vCPU)
    Type: Number
    Default: 256
    AllowedValues:
      - 256
      - 512
      - 1024
      - 2048
      - 4096

  ContainerMemory:
    Description: Memory for the container in MB
    Type: Number
    Default: 512
    AllowedValues:
      - 512
      - 1024
      - 2048
      - 4096
      - 8192

  DesiredCount:
    Description: Number of container tasks to run
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 10

  JWTSecretKey:
    Description: JWT secret key for authentication (generate a random string)
    Type: String
    NoEcho: true
    MinLength: 32
    ConstraintDescription: Must be at least 32 characters long

Conditions:
  ShouldCreateECR: !Equals [!Ref CreateECRRepository, 'true']

Resources:
  # ECR Stack (Optional)
  ECRStack:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldCreateECR
    Properties:
      TemplateURL: !Sub https://${TemplateS3Bucket}.s3.${AWS::Region}.amazonaws.com/${TemplateS3KeyPrefix}ecr.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ImageTagMutability: !Ref ImageTagMutability
        LifecyclePolicyMaxImageCount: 10
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-ecr-stack

  # VPC Stack
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${TemplateS3Bucket}.s3.${AWS::Region}.amazonaws.com/${TemplateS3KeyPrefix}vpc.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-vpc-stack

  # Security Groups Stack
  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub https://${TemplateS3Bucket}.s3.${AWS::Region}.amazonaws.com/${TemplateS3KeyPrefix}security-groups.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VPC: !GetAtt VPCStack.Outputs.VPC
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-sg-stack

  # RDS Stack
  RDSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - SecurityGroupsStack
    Properties:
      TemplateURL: !Sub https://${TemplateS3Bucket}.s3.${AWS::Region}.amazonaws.com/${TemplateS3KeyPrefix}rds.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        RDSSecurityGroup: !GetAtt SecurityGroupsStack.Outputs.RDSSecurityGroup
        DBInstanceClass: !Ref DBInstanceClass
        DBPassword: !Ref DBPassword
        AllocatedStorage: !Ref AllocatedStorage
        MultiAZ: !Ref MultiAZ
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-rds-stack

  # ALB Stack
  ALBStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - SecurityGroupsStack
    Properties:
      TemplateURL: !Sub https://${TemplateS3Bucket}.s3.${AWS::Region}.amazonaws.com/${TemplateS3KeyPrefix}alb.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VPC: !GetAtt VPCStack.Outputs.VPC
        PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2
        ALBSecurityGroup: !GetAtt SecurityGroupsStack.Outputs.ALBSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-alb-stack

  # ECS Stack
  ECSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - SecurityGroupsStack
      - RDSStack
      - ALBStack
    Properties:
      TemplateURL: !Sub https://${TemplateS3Bucket}.s3.${AWS::Region}.amazonaws.com/${TemplateS3KeyPrefix}ecs.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        ECSSecurityGroup: !GetAtt SecurityGroupsStack.Outputs.ECSSecurityGroup
        TargetGroupArn: !GetAtt ALBStack.Outputs.TargetGroupArn
        ContainerImage: !Ref ContainerImage
        ContainerCpu: !Ref ContainerCpu
        ContainerMemory: !Ref ContainerMemory
        DesiredCount: !Ref DesiredCount
        DBEndpoint: !GetAtt RDSStack.Outputs.DBInstanceEndpoint
        DBPort: !GetAtt RDSStack.Outputs.DBInstancePort
        DBName: !GetAtt RDSStack.Outputs.DBName
        DBUsername: !GetAtt RDSStack.Outputs.DBUsername
        DBPassword: !Ref DBPassword
        JWTSecretKey: !Ref JWTSecretKey
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-ecs-stack

Outputs:
  ApplicationURL:
    Description: URL of the Cloud Optimizer application
    Value: !GetAtt ALBStack.Outputs.LoadBalancerURL

  LoadBalancerDNS:
    Description: DNS name of the Application Load Balancer
    Value: !GetAtt ALBStack.Outputs.LoadBalancerDNS

  DatabaseEndpoint:
    Description: RDS PostgreSQL endpoint
    Value: !GetAtt RDSStack.Outputs.DBInstanceEndpoint

  ECSCluster:
    Description: ECS Cluster name
    Value: !GetAtt ECSStack.Outputs.ECSClusterName

  ECSService:
    Description: ECS Service name
    Value: !GetAtt ECSStack.Outputs.ECSServiceName

  VPCId:
    Description: VPC ID
    Value: !GetAtt VPCStack.Outputs.VPC

  ECRRepositoryUri:
    Description: ECR Repository URI (if created)
    Condition: ShouldCreateECR
    Value: !GetAtt ECRStack.Outputs.RepositoryUri

  ECRRepositoryName:
    Description: ECR Repository Name (if created)
    Condition: ShouldCreateECR
    Value: !GetAtt ECRStack.Outputs.RepositoryName

  DeploymentInstructions:
    Description: Next steps after deployment
    Value: !Sub |
      1. Wait for all stacks to complete (typically 8-10 minutes)
      2. Access your application at: ${ALBStack.Outputs.LoadBalancerURL}
      3. Monitor ECS tasks in the AWS Console
      4. Check CloudWatch logs at /ecs/${EnvironmentName} for application logs
      5. Update the ContainerImage parameter with your actual Docker image when ready
