"""Add AWS accounts, scan jobs, and findings tables

Revision ID: 8b2566889924
Revises: d62d8b44f851
Create Date: 2025-12-02 01:42:23.754833

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b2566889924"
down_revision: Union[str, None] = "d62d8b44f851"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "compliance_frameworks",
        sa.Column(
            "framework_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("framework_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "aws_accounts",
        sa.Column(
            "account_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("aws_account_id", sa.String(length=12), nullable=False),
        sa.Column("friendly_name", sa.String(length=255), nullable=True),
        sa.Column(
            "connection_type",
            sa.Enum("IAM_ROLE", "ACCESS_KEYS", name="connection_type"),
            nullable=False,
        ),
        sa.Column("role_arn", sa.String(length=2048), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("access_key_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("secret_key_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "ACTIVE", "ERROR", "DISCONNECTED", name="connection_status"
            ),
            nullable=False,
        ),
        sa.Column("last_validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("default_region", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("account_id"),
    )
    op.create_index(
        op.f("ix_aws_accounts_user_id"), "aws_accounts", ["user_id"], unique=False
    )
    op.create_table(
        "compliance_controls",
        sa.Column(
            "control_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("framework_id", sa.UUID(), nullable=False),
        sa.Column("control_number", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["framework_id"],
            ["compliance_frameworks.framework_id"],
        ),
        sa.PrimaryKeyConstraint("control_id"),
    )
    op.create_table(
        "rule_compliance_mappings",
        sa.Column(
            "mapping_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("rule_id", sa.String(length=50), nullable=False),
        sa.Column("control_id", sa.UUID(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["control_id"],
            ["compliance_controls.control_id"],
        ),
        sa.PrimaryKeyConstraint("mapping_id"),
    )
    op.create_index(
        op.f("ix_rule_compliance_mappings_rule_id"),
        "rule_compliance_mappings",
        ["rule_id"],
        unique=False,
    )
    op.create_table(
        "scan_jobs",
        sa.Column(
            "job_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("aws_account_id", sa.UUID(), nullable=False),
        sa.Column(
            "scan_type",
            sa.Enum("SECURITY", "COST", "FULL", name="scan_type"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="scan_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "services_to_scan", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("total_findings", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["aws_account_id"], ["aws_accounts.account_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_index(
        op.f("ix_scan_jobs_aws_account_id"),
        "scan_jobs",
        ["aws_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scan_jobs_user_id"), "scan_jobs", ["user_id"], unique=False
    )
    op.create_table(
        "cost_findings",
        sa.Column(
            "finding_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("scan_job_id", sa.UUID(), nullable=False),
        sa.Column("aws_account_id", sa.UUID(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "UNUSED",
                "RIGHTSIZING",
                "RESERVED",
                "SAVINGS_PLAN",
                "SPOT",
                name="costcategory",
            ),
            nullable=False,
        ),
        sa.Column("service", sa.String(length=50), nullable=False),
        sa.Column("resource_id", sa.String(length=500), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("region", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column("current_cost", sa.Float(), nullable=False),
        sa.Column("estimated_savings", sa.Float(), nullable=False),
        sa.Column("savings_percentage", sa.Float(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["aws_account_id"],
            ["aws_accounts.account_id"],
        ),
        sa.ForeignKeyConstraint(
            ["scan_job_id"],
            ["scan_jobs.job_id"],
        ),
        sa.PrimaryKeyConstraint("finding_id"),
    )
    op.create_table(
        "cost_summaries",
        sa.Column(
            "summary_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("scan_job_id", sa.UUID(), nullable=False),
        sa.Column("aws_account_id", sa.UUID(), nullable=False),
        sa.Column("total_monthly_cost", sa.Float(), nullable=False),
        sa.Column("total_potential_savings", sa.Float(), nullable=False),
        sa.Column(
            "savings_by_category",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "cost_by_service", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["aws_account_id"],
            ["aws_accounts.account_id"],
        ),
        sa.ForeignKeyConstraint(
            ["scan_job_id"],
            ["scan_jobs.job_id"],
        ),
        sa.PrimaryKeyConstraint("summary_id"),
    )
    op.create_table(
        "findings",
        sa.Column(
            "finding_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("scan_job_id", sa.UUID(), nullable=False),
        sa.Column("aws_account_id", sa.UUID(), nullable=False),
        sa.Column("rule_id", sa.String(length=255), nullable=False),
        sa.Column(
            "finding_type",
            sa.Enum("SECURITY", "COST", name="finding_type"),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO", name="finding_severity"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "RESOLVED",
                "SUPPRESSED",
                "FALSE_POSITIVE",
                name="finding_status",
            ),
            nullable=False,
        ),
        sa.Column("service", sa.String(length=100), nullable=False),
        sa.Column("resource_type", sa.String(length=255), nullable=False),
        sa.Column("resource_id", sa.String(length=500), nullable=False),
        sa.Column("resource_arn", sa.String(length=500), nullable=True),
        sa.Column("region", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column(
            "evidence",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "compliance_frameworks",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("potential_savings", sa.Float(), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["aws_account_id"], ["aws_accounts.account_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["scan_job_id"], ["scan_jobs.job_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("finding_id"),
    )
    op.create_index(
        "idx_finding_dedup",
        "findings",
        ["aws_account_id", "rule_id", "resource_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_findings_aws_account_id"), "findings", ["aws_account_id"], unique=False
    )
    op.create_index(
        op.f("ix_findings_finding_type"), "findings", ["finding_type"], unique=False
    )
    op.create_index(op.f("ix_findings_region"), "findings", ["region"], unique=False)
    op.create_index(
        op.f("ix_findings_resource_id"), "findings", ["resource_id"], unique=False
    )
    op.create_index(op.f("ix_findings_rule_id"), "findings", ["rule_id"], unique=False)
    op.create_index(
        op.f("ix_findings_scan_job_id"), "findings", ["scan_job_id"], unique=False
    )
    op.create_index(op.f("ix_findings_service"), "findings", ["service"], unique=False)
    op.create_index(
        op.f("ix_findings_severity"), "findings", ["severity"], unique=False
    )
    op.create_index(op.f("ix_findings_status"), "findings", ["status"], unique=False)

    # Drop legacy tables if they exist (using raw SQL for IF EXISTS support)
    connection = op.get_bind()
    legacy_tables = [
        "cg_entity_chunks",
        "cg_relationships",
        "cg_chunks",
        "cg_entities",
        "cg_entity_types",
        "cg_relationship_types",
        "cg_documents",
        "cg_document_sources",
        "organizations",
    ]
    for table in legacy_tables:
        connection.execute(sa.text(f"DROP TABLE IF EXISTS {table} CASCADE"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cg_document_sources",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('cg_document_sources_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("organization_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("title", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "source_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("vendor", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "service", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "category", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "tags", postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_updated", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name="cg_document_sources_organization_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="cg_document_sources_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "cg_entities",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('cg_entities_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("organization_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("type_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "properties",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "confidence",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("1.0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name="cg_entities_organization_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["type_id"], ["cg_entity_types.id"], name="cg_entities_type_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="cg_entities_pkey"),
        sa.UniqueConstraint(
            "organization_id",
            "name",
            "type_id",
            name="cg_entities_organization_id_name_type_id_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_index(op.f("idx_entities_type"), "cg_entities", ["type_id"], unique=False)
    op.create_index(op.f("idx_entities_name"), "cg_entities", ["name"], unique=False)
    op.create_table(
        "cg_entity_chunks",
        sa.Column("entity_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("chunk_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "relevance_score",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("1.0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["chunk_id"], ["cg_chunks.id"], name=op.f("cg_entity_chunks_chunk_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["cg_entities.id"],
            name=op.f("cg_entity_chunks_entity_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "entity_id", "chunk_id", name=op.f("cg_entity_chunks_pkey")
        ),
    )
    op.create_table(
        "cg_documents",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('cg_documents_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("source_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("organization_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "processed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "processing_status",
            sa.VARCHAR(length=50),
            server_default=sa.text("'pending'::character varying"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name="cg_documents_organization_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["cg_document_sources.id"],
            name="cg_documents_source_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="cg_documents_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "cg_chunks",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("document_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("organization_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("chunk_index", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("start_pos", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("end_pos", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["cg_documents.id"],
            name=op.f("cg_chunks_document_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("cg_chunks_organization_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("cg_chunks_pkey")),
    )
    op.create_index(
        op.f("idx_chunks_embedding"),
        "cg_chunks",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_using="ivfflat",
    )
    op.create_table(
        "cg_relationships",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("source_entity_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("target_entity_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("type_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "properties",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "confidence",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("1.0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("cg_relationships_organization_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["source_entity_id"],
            ["cg_entities.id"],
            name=op.f("cg_relationships_source_entity_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["target_entity_id"],
            ["cg_entities.id"],
            name=op.f("cg_relationships_target_entity_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["cg_relationship_types.id"],
            name=op.f("cg_relationships_type_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("cg_relationships_pkey")),
        sa.UniqueConstraint(
            "organization_id",
            "source_entity_id",
            "target_entity_id",
            "type_id",
            name=op.f(
                "cg_relationships_organization_id_source_entity_id_target_en_key"
            ),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_relationships_target"),
        "cg_relationships",
        ["target_entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_relationships_source"),
        "cg_relationships",
        ["source_entity_id"],
        unique=False,
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("organizations_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("organizations_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "cg_relationship_types",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("cg_relationship_types_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("cg_relationship_types_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "cg_entity_types",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("cg_entity_types_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("cg_entity_types_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_index(op.f("ix_findings_status"), table_name="findings")
    op.drop_index(op.f("ix_findings_severity"), table_name="findings")
    op.drop_index(op.f("ix_findings_service"), table_name="findings")
    op.drop_index(op.f("ix_findings_scan_job_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_rule_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_resource_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_region"), table_name="findings")
    op.drop_index(op.f("ix_findings_finding_type"), table_name="findings")
    op.drop_index(op.f("ix_findings_aws_account_id"), table_name="findings")
    op.drop_index("idx_finding_dedup", table_name="findings")
    op.drop_table("findings")
    op.drop_table("cost_summaries")
    op.drop_table("cost_findings")
    op.drop_index(op.f("ix_scan_jobs_user_id"), table_name="scan_jobs")
    op.drop_index(op.f("ix_scan_jobs_aws_account_id"), table_name="scan_jobs")
    op.drop_table("scan_jobs")
    op.drop_index(
        op.f("ix_rule_compliance_mappings_rule_id"),
        table_name="rule_compliance_mappings",
    )
    op.drop_table("rule_compliance_mappings")
    op.drop_table("compliance_controls")
    op.drop_index(op.f("ix_aws_accounts_user_id"), table_name="aws_accounts")
    op.drop_table("aws_accounts")
    op.drop_table("compliance_frameworks")
    # ### end Alembic commands ###
